/* ACTION TYPES */

export const ITEMS_IS_ERRORED = 'ITEMS_IS_ERRORED';
export const ITEMS_IS_LOADING = 'ITEMS_IS_LOADING';
export const ITEMS_FETCH_DATA_SUCCESS = 'ITEMS_FETCH_DATA_SUCCESS';
export const ADD_POST = 'ADD_POST';
